// analyticsTypes.js

export const FETCH_ANALYTICS_DATA = "FETCH_ANALYTICS_DATA";
export const SET_ANALYTICS_LOADING = "SET_ANALYTICS_LOADING";
export const SET_ANALYTICS_ERROR = "SET_ANALYTICS_ERROR";
export const UPDATE_CHATBOT_PERFORMANCE = "UPDATE_CHATBOT_PERFORMANCE";
export const SET_USER_ENGAGEMENT_DATA = "SET_USER_ENGAGEMENT_DATA";
export const SET_SENTIMENT_ANALYSIS = "SET_SENTIMENT_ANALYSIS";
