// frontend/src/store/types/automationTypes.js

export const FETCH_AUTOMATIONS = "FETCH_AUTOMATIONS";
export const CREATE_AUTOMATION = "CREATE_AUTOMATION";
export const UPDATE_AUTOMATION = "UPDATE_AUTOMATION";
export const DELETE_AUTOMATION = "DELETE_AUTOMATION";
export const SET_AUTOMATION_LOADING = "SET_AUTOMATION_LOADING";
export const SET_AUTOMATION_ERROR = "SET_AUTOMATION_ERROR";
