// chatbotTypes.js

export const CHATBOT_SEND_MESSAGE = "CHATBOT_SEND_MESSAGE";
export const CHATBOT_RECEIVE_MESSAGE = "CHATBOT_RECEIVE_MESSAGE";
export const CHATBOT_SET_LOADING = "CHATBOT_SET_LOADING";
export const CHATBOT_SET_ERROR = "CHATBOT_SET_ERROR";
export const CHATBOT_UPDATE_CONTEXT = "CHATBOT_UPDATE_CONTEXT";
export const CHATBOT_RESET_SESSION = "CHATBOT_RESET_SESSION";
