// integrationsTypes.js

export const FETCH_INTEGRATIONS = "FETCH_INTEGRATIONS";
export const ADD_INTEGRATION = "ADD_INTEGRATION";
export const REMOVE_INTEGRATION = "REMOVE_INTEGRATION";
export const UPDATE_INTEGRATION = "UPDATE_INTEGRATION";
export const SET_INTEGRATIONS_LOADING = "SET_INTEGRATIONS_LOADING";
export const SET_INTEGRATIONS_ERROR = "SET_INTEGRATIONS_ERROR";
