// types/integrationsTypes.js

// Action Types for Integrations
export const INTEGRATIONS_REQUEST = 'INTEGRATIONS_REQUEST';
export const INTEGRATIONS_SUCCESS = 'INTEGRATIONS_SUCCESS';
export const INTEGRATIONS_FAILURE = 'INTEGRATIONS_FAILURE';

export const ADD_INTEGRATION = 'ADD_INTEGRATION';
export const REMOVE_INTEGRATION = 'REMOVE_INTEGRATION';
export const UPDATE_INTEGRATION = 'UPDATE_INTEGRATION';

export const FETCH_INTEGRATION_STATUS = 'FETCH_INTEGRATION_STATUS';
export const INTEGRATION_STATUS_SUCCESS = 'INTEGRATION_STATUS_SUCCESS';
export const INTEGRATION_STATUS_FAILURE = 'INTEGRATION_STATUS_FAILURE';

export const TEST_INTEGRATION_CONNECTION = 'TEST_INTEGRATION_CONNECTION';
export const TEST_INTEGRATION_SUCCESS = 'TEST_INTEGRATION_SUCCESS';
export const TEST_INTEGRATION_FAILURE = 'TEST_INTEGRATION_FAILURE';

// Action Types for Specific Integrations (e.g., CRM, Payment Gateway)
export const CONNECT_CRMSYSTEM = 'CONNECT_CRMSYSTEM';
export const DISCONNECT_CRMSYSTEM = 'DISCONNECT_CRMSYSTEM';
export const CONNECT_PAYMENT_GATEWAY = 'CONNECT_PAYMENT_GATEWAY';
export const DISCONNECT_PAYMENT_GATEWAY = 'DISCONNECT_PAYMENT_GATEWAY';
