// marketplaceTypes.js

export const FETCH_MARKETPLACE_ITEMS = "FETCH_MARKETPLACE_ITEMS";
export const ADD_MARKETPLACE_ITEM = "ADD_MARKETPLACE_ITEM";
export const REMOVE_MARKETPLACE_ITEM = "REMOVE_MARKETPLACE_ITEM";
export const UPDATE_MARKETPLACE_ITEM = "UPDATE_MARKETPLACE_ITEM";
export const SET_MARKETPLACE_LOADING = "SET_MARKETPLACE_LOADING";
export const SET_MARKETPLACE_ERROR = "SET_MARKETPLACE_ERROR";
