// notificationsTypes.js

export const FETCH_NOTIFICATIONS = "FETCH_NOTIFICATIONS";
export const MARK_NOTIFICATION_AS_READ = "MARK_NOTIFICATION_AS_READ";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const SET_NOTIFICATIONS_LOADING = "SET_NOTIFICATIONS_LOADING";
export const SET_NOTIFICATIONS_ERROR = "SET_NOTIFICATIONS_ERROR";
