// securityTypes.js

export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const VALIDATE_AUTH_TOKEN = "VALIDATE_AUTH_TOKEN";
export const USER_HAS_PERMISSION = "USER_HAS_PERMISSION";
export const FETCH_USER_PERMISSIONS = "FETCH_USER_PERMISSIONS";
export const SET_SECURITY_ERROR = "SET_SECURITY_ERROR";
