// settingsTypes.js

export const UPDATE_THEME = "UPDATE_THEME";
export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";
export const UPDATE_PRIVACY_SETTINGS = "UPDATE_PRIVACY_SETTINGS";
export const UPDATE_NOTIFICATION_SETTINGS = "UPDATE_NOTIFICATION_SETTINGS";
export const SET_SETTINGS_LOADING = "SET_SETTINGS_LOADING";
export const SET_SETTINGS_ERROR = "SET_SETTINGS_ERROR";
