// userTypes.js

// Action types for user-related actions
export const LOGIN_REQUEST = 'USER/LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'USER/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'USER/LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'USER/LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'USER/LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'USER/LOGOUT_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'USER/UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'USER/UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'USER/UPDATE_PROFILE_FAILURE';

export const FETCH_USER_PROFILE_REQUEST = 'USER/FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_SUCCESS = 'USER/FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'USER/FETCH_USER_PROFILE_FAILURE';

export const SET_USER_PREFERENCES = 'USER/SET_USER_PREFERENCES';
